logging:
  level:
    ru:
      practicum: debug
spring:
  banner:
    location: banner-production.txt
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always